# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sf/substreams/v1/package.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from sf.substreams.v1 import modules_pb2 as sf_dot_substreams_dot_v1_dot_modules__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esf/substreams/v1/package.proto\x12\x10sf.substreams.v1\x1a google/protobuf/descriptor.proto\x1a\x1esf/substreams/v1/modules.proto\"\xba\x02\n\x07Package\x12\x45\n\x0bproto_files\x18\x01 \x03(\x0b\x32$.google.protobuf.FileDescriptorProtoR\nprotoFiles\x12\x18\n\x07version\x18\x05 \x01(\x04R\x07version\x12\x33\n\x07modules\x18\x06 \x01(\x0b\x32\x19.sf.substreams.v1.ModulesR\x07modules\x12\x41\n\x0bmodule_meta\x18\x07 \x03(\x0b\x32 .sf.substreams.v1.ModuleMetadataR\nmoduleMeta\x12\x44\n\x0cpackage_meta\x18\x08 \x03(\x0b\x32!.sf.substreams.v1.PackageMetadataR\x0bpackageMetaJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\"c\n\x0fPackageMetadata\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n\x03\x64oc\x18\x04 \x01(\tR\x03\x64oc\"G\n\x0eModuleMetadata\x12#\n\rpackage_index\x18\x01 \x01(\x04R\x0cpackageIndex\x12\x10\n\x03\x64oc\x18\x02 \x01(\tR\x03\x64ocBFZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreamsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.substreams.v1.package_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZDgithub.com/streamingfast/substreams/pb/sf/substreams/v1;pbsubstreams'
  _PACKAGE._serialized_start=119
  _PACKAGE._serialized_end=433
  _PACKAGEMETADATA._serialized_start=435
  _PACKAGEMETADATA._serialized_end=534
  _MODULEMETADATA._serialized_start=536
  _MODULEMETADATA._serialized_end=607
# @@protoc_insertion_point(module_scope)
